import { Box, Center, Group } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import Iframe from "react-iframe";
import NextButton from "../components/NextButton";
const Attack: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Blockscout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box mt={60}>
        <Center>
          <Group>
            <NextButton
              href="/"
              title="51% Attack"
              color="red"
              size="xl"
            />
            <NextButton
              href="/"
              title="DAO Attack"
              color="red"
              size="xl"
            />
          </Group>
        </Center>
        </Box>
      </main>
    </div>
  );
};

export default Attack;
