import { Box, Center } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Blockchain } from "../components";
import web3 from "../web3/web3Provider";

// Here is a subscription object. Look here for documentation: https://web3js.readthedocs.io/en/v1.8.1/web3-eth-subscribe.html#eth-subscribe

const Home: NextPage = () => {
  const [nodes, setNodes] = useState([
    " ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ]);
  const [blocknumber, setBlocknumber] = useState([]);

  return (
    <div>
      <Head>
        <title>Ethereum Attack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ padding: 15 }}>
          <Center>
            {/* Chain Animation with hashes and nodes as props */}
            <Blockchain hashes={blocknumber} nodes={nodes} />
          </Center>
        </Box>
      </main>
    </div>
  );
};

export default Home;
