import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import AnimeChain from "../components/animatedChain";
import { Box, Center } from "@mantine/core";
import web3 from '../utils/web3/web3Provider';
import { BlockHeader } from "web3-eth";
// Here is a subscription object. Look here for documentation: https://web3js.readthedocs.io/en/v1.8.1/web3-eth-subscribe.html#eth-subscribe

const Subscription = web3.eth.subscribe('newBlockHeaders', (error, result: BlockHeader) => {
  if (!error) {
    console.log(result); //result.blockNumber for block number
  }
  else 
  {
    console.log(error);
  }
});


const Home: NextPage = () => {
  const [nodes, setNodes] = useState([
    " ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ]);
  const [blocknumber, setBlocknumber] = useState([]);

  //let subscription = web3.eth.subscribe(
  //  "newBlockHeaders",
   // function (error, results) {
    //  console.log(results);
  //  }
 // );

  return (
    <div>
      <Head>
        <title>Ethereum Attack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box mt={60}>
        <Center>
          {/* Chain Animation with hashes and nodes as props */}
          <AnimeChain hashes={blocknumber} nodes={nodes} />
        </Center>
        </Box>
      </main>
    </div>
  );
};

export default Home;
